### ISSUE TITLE
Simplify subclass axioms and remove .obo file release until this is done

### ISSUE THREAD

**Issue by cmungall** [insect-morphology/lepao#10]
cuticular internal depression

SubClassOf:
'region of cuticle'
 and ('part of' some 'proximal side')
 and ('bearer of' some concave)
'part of' some 'insect region of integument'
'part of' some 'chitin-based cuticle'

I strongly recommend that all subclass axioms are written in equivalent form that dosn't use IntersectionOf

 1. CID subClassOf 'region of cuticle'
 2. CID 'part of' some 'proximal side'

This is equivalent and will make your ontology much more usable to any consumer that is not using a reasoner

I believe running https://robot.obolibrary.org/relax should take care of this - if you are using a standard ODK template not sure why we are not seeing the simplified form

**Comment by JCGiron** [comment]
Corrected in the latest AISM release (v2021-12-13).
The places were we left composed axioms are where specification of a region or margin are necessary.
