### ISSUE TITLE
consider moving some terms from out of space into structure

### ISSUE THREAD

**Issue by cmungall** [insect-morphology/lepao#11]
![image](https://user-images.githubusercontent.com/50745/144097967-c783c84e-4970-4ad8-8e6c-d639b180956f.png)

In general I recommend very conservative usage of immaterial entities, there are all kinds of OWL traps in using them

There are some particular problems here:

 - anus is treated as a space which is incompatible with the most widely used insect anatomy 
 [Dmel anus](https://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00047153) cc 
 - chambers such as the genital chamber are treated as structures not spaces in uberon fbbt etc
 - in fact in your own definition of genital chamber you say it is a region

Also, if you are following philosophical upper ontologies and dividing material and immaterial entities I recommend adding disjointness axioms to detect any problems early lmk if you want help with this (reasoning with uberon should also do this)

**Comment by cmungall** [comment]
oh I see this should instead go in the AISM tracker https://github.com/insect-morphology/aism/issues

**Comment by JCGiron** [comment]
Corrected in the latest AISM release (v2021-12-13) by using [orifice](http://purl.obolibrary.org/obo/UBERON_0000161) instead of ['anatomical space'](http://purl.obolibrary.org/obo/UBERON_0000464).
